[package]
name = "fox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fox_core = { path = "../fox_core"}
fox_macro = { path = "../fox_macro"}
